package springboottemplate.seeddata;

public class Names {
    public static String names = """
            Amber Roberts
            Erna Feest
            Ernestina Mraz
            Lorna Leuschke
            Adonis Harber
            Demetrius Farrell
            Laurence Prosacco
            Noemy Stamm
            Dakota Stamm
            Mustafa Hettinger
            Otilia Koelpin
            Michele Jacobson
            Rory Leannon
            Akeem Koepp
            Watson Welch
            Jonas West
            Vernice Jacobs
            Kaylie Eichmann
            Brigitte Schiller
            Evalyn Durgan
            Maud Ullrich
            Camila Haley
            Bud Halvorson
            Elsie Will
            Jeramie Eichmann
            Dexter Goyette
            Bethel Fadel
            Ola Feeney
            Donato Brekke
            Colten Keebler
            Nelle McGlynn
            Myrl Walsh
            Janice Gulgowski
            Donnell Osinski
            Claudine Mayert
            Justus Breitenberg
            Gage Hilpert
            Jordane Marquardt
            Ima Bins
            Chelsea Reilly
            Myrna Schulist
            Hattie Hand
            Dean Zieme
            Jimmie Zboncak
            Novella Gibson
            Sabryna Stamm
            Toby Sanford
            Violette Purdy
            Assunta Lebsack
            Raven Trantow
            Iliana Klein
            Quincy Ankunding
            Jaleel Bernhard
            Dax Gibson
            Danial Mills
            America Hamill
            Yazmin Jenkins
            Jaquelin Ziemann
            Melba Eichmann
            George Hyatt
            Clara Kuhic
            Ben Franecki
            Noemi Mayer
            Cleveland Pollich
            Gretchen Kertzmann
            Mariela Hessel
            Vilma Heaney
            Ursula Buckridge
            Arturo Lebsack
            Rodolfo O'Reilly
            Eldora Altenwerth
            Dominique Rodriguez
            Brendon Mitchell
            Josie Dooley
            Orval Huels
            Elizabeth Ebert
            Scot Lakin
            Eleonore Hartmann
            Misael Strosin
            Jarrell Skiles
            Princess Dibbert
            Edward Reinger
            Maya Borer
            Jason Heathcote
            Ali Tremblay
            Godfrey Stracke
            Lottie Pagac
            Hailey Schneider
            Shaina Raynor
            Ezra Kautzer
            Royal Block
            Kyleigh Bernhard
            Gerard Kuhlman
            Shayna Kunze
            Corine Lemke
            Noemie Fisher
            Cyril Stanton
            Fabian Mitchell
            Damion Lubowitz
            Marta Jerde
            Polly Koepp
            Maxine Ritchie
            Josue Jones
            Wilhelm Labadie
            Addie Bashirian
            Heber Mraz
            Liliana Kulas
            Maymie Gerhold
            Marcella Wiza
            Tanya Casper
            Eusebio Goodwin
            Brody Quigley
            Cristal Beatty
            Jaquelin Doyle
            Carmella Christiansen
            Jarret Friesen
            Dashawn Harber
            Carmela Aufderhar
            Alayna Terry
            Morgan Ratke
            Arvilla Bednar
            Norris Kris
            Mose Quigley
            Lacey Greenholt
            Joanny Kulas
            Norval Grimes
            Natalia Cummings
            Jalyn Durgan
            Arianna Casper
            Mossie Abbott
            Wyatt Wintheiser
            Kyler Borer
            Sigmund Adams
            Clifford Schoen
            Thea Anderson
            Janae Heaney
            Roscoe Funk
            Tara Towne
            Brice Rohan
            Felicita Koelpin
            Else Abernathy
            Joaquin Koss
            Amanda Becker
            Dan Turcotte
            Alford Willms
            Benedict Glover
            Juliet Koch
            Veronica Douglas
            Deangelo Huel
            Bridget Lakin
            Blaze Marks
            Jerod Gerlach
            Malika Heidenreich
            Delphine Larson
            Elvis Von
            Jimmy Donnelly
            Tyrel Zulauf
            Beulah Haley
            Leo Schinner
            Juliet Bradtke
            Constance Wilderman
            Kathleen Ratke
            Oma O'Keefe
            Catherine Hackett
            Keanu Kuhn
            Rachelle Runte
            Julie Purdy
            Annabell Miller
            Maribel Stroman
            Tyson Ward
            Sanford Doyle
            Janick Blick
            Braeden Kreiger
            Teresa McLaughlin
            Josiah Huels
            Keon Crona
            Destinee Reilly
            Enos Carroll
            Jett Morar
            Libbie Von
            Lexi Howe
            Maxwell Mayer
            Sedrick Krajcik
            Mattie Collier
            Erich Moore
            Cleta Goldner
            Rylee Deckow
            Anita Sipes
            Shaylee Romaguera
            Kassandra Kiehn
            Clint Koepp
            Alena Hilll
            Delphia Dicki
            Cristal Blick
            Weston Herzog
            Alfredo Kreiger
            Earline Heaney
            Kane Zulauf
            Jessica Kulas
            Tamara Goyette
            """;
}
